name: Release please

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  release-please:
    name: Release please
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Create release PR
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
